"""
Django settings for knowledgeBox project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import cohere
from pathlib import Path
import os
# load env from dotenv
import dotenv


dotenv.load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


ALLOWED_HOSTS = ['*']

CORS_ORIGIN_ALLOW_ALL = False

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "searchresolver",
    "sources",
    "corsheaders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]
CORS_ALLOWED_ORIGINS = [
    'https://qna-web.vercel.app',
    'https://ben-bites.vercel.app',
    'https://bens.askoracle.app'
]

ROOT_URLCONF = "knowledgeBox.urls"
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "knowledgeBox.wsgi.application"

STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
MEDIA_ROOT = 'media/'
SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-(ydvuf^1r&tnugzucqq)07+@ba9#90vskgyc2lg0_-m%_n(8&+")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", True)
OPEN_AI_KEY = os.environ.get("OPEN_AI_KEY", "sk-")  # openai key
COHERE_API_KEY = os.environ.get("COHERE_API_KEY", "")  # cohere key
ASSEMBLY_API_KEY = os.environ.get("ASSEMBLY_API_KEY", "")  # assemblyai key


# PROMPT = os.environ.get("PROMPT", """Answer the given question with the help of contexts. Add link to the context from which the answer is derived in the end of the answer. If the answer is not contained within the text below, say, "I don't know". Answer the question in simple language, verbosely and accurately.

# All Contexts:

# $CONTEXT

# Q: $query
# A:""")

PROMPT = os.environ.get("PROMPT", """Answer the given question with the help of contexts. If the answer is not contained within the text below, say, "I don't know". Answer the question in simple language, verbosely and accurately.

ALL Contexts:

$CONTEXT

Q: $query
A:""")

MAX_COMPLETION_LENGTH = int(os.environ.get("MAX_COMPLETION_LENGTH", 4000))
COMPLETIONS_MODEL = os.environ.get("COMPLETIONS_MODEL", "text-davinci-003")
MAX_CONTEXT_LENGTH = int(os.environ.get("MAX_CONTEXT_LENGTH", 4000))

COHERE_CLIENT = cohere.Client(COHERE_API_KEY)
EMBEDDING_MODEL = os.environ.get(
    "EMBEDDING_MODEL", "openai")
MAX_EMBEDDING_LENGTH = int(os.environ.get("MAX_EMBEDDING_LENGTH", 1200))


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
